
name: Testing workflow

on:
  push:
    branches: [ "main" ]
    paths:
      - 'testes/**'    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Hello, world!
